- name: Install Python3 for Ansible
  hosts: all
  become: true
  tasks:
    - name: Install python3 and python3-pip on CentOS
      yum:
        name:
          - python3
          - python3-pip
        state: present
