---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: instance
    image: ubuntu:22.04
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  playbooks:
    converge: ../../playbook.yml

verifier:
  enabled: false
