---
dependency:
  name: galaxy

driver:
  name: podman

platforms:
  - name: instance
    image: docker.io/library/ubuntu:22.04
    privileged: true

provisioner:
  name: ansible
  playbooks:
    converge: ../../playbook.yml
    destroy: playbooks/destroy.yml

verifier:
  name: ansible
